version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  jira:
    depends_on:
      - postgresql
    image: "teamatldocker/jira:8.5.1"
    restart: unless-stopped
    environment:
      JIRA_DATABASE_URL: postgresql://jira@postgresql/jiradb
      JIRA_DB_PASSWORD: ${JIRA_DB_PASSWORD}
      SETENV_JVM_MINIMUM_MEMORY: ${JVM_MINIMUM_MEMORY:-2048m}
      SETENV_JVM_MAXIMUM_MEMORY: ${JVM_MAXIMUM_MEMORY:-4096m}
      JIRA_PROXY_NAME: ${JIRA_PROXY_NAME}
      JIRA_PROXY_PORT: ${JIRA_PROXY_PORT}
      JIRA_PROXY_SCHEME: ${JIRA_PROXY_SCHEME}
    ports:
     - "8080:8080"
    volumes:
      - "${BASE_PATH:-/data}/jira:/var/atlassian/jira"
    logging: *default-logging
    networks:
      - default
    labels:
      - traefik.enable=${TRAEFIK_ENABLE:-true}
      - traefik.http.routers.jira.entrypoints=https
      - traefik.http.routers.jira.tls.certresolver=${TRAEFIK_CERT_RESOLVER:-default}
      - traefik.http.routers.jira.tls=true
      - traefik.http.routers.jira.rule=${JIRA_URL_CONFIG:-Host(`jira.example.com`)}

  postgresql:
    image: "postgres:10.9-alpine"
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-jira}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-jiradb}
      POSTGRES_ENCODING: ${POSTGRES_ENCODING:-UNICODE}
      POSTGRES_COLLATE: ${POSTGRES_COLLATE:-C}
      POSTGRES_COLLATE_TYPE: ${POSTGRES_COLLATE_TYPE:-C}
    logging: *default-logging
    networks:
      - default
    volumes:
    - "${BASE_PATH:-/data}/postgresqldata:/var/lib/postgresql/data"

  traefik:
    image: traefik:2.0.1
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8081:8080
    networks:
      - default
      - web
    logging: *default-logging
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik


# run docker network create web before
networks:
  web:
    external: true

